[platformio]
default_envs =
	GL-C-211WL
	GL-C-615WL ; = GL-C-015WL-M
	GL-C-616WL
	GL-C-618WL
	GL-C-620WL

[gledopto_flags]
build_flags =
 -D WLED_BRAND="\"GLEDOPTO\""
 -D SERVERNAME='"WLED-Gledopto"'
 -D DEFAULT_AP_SSID="\"WLED-AP\"" 

; microphone configuration
[mic_pdm]
build_flags =
	  -D UM_AUDIOREACTIVE_ENABLE
	  -D SR_DMTYPE=5
	  -D I2S_SDPIN=32
	  -D I2S_WSPIN=15
	  -D I2S_CKPIN=-1
	  -D MCLK_PIN=-1
	  -D SR_AGC=2
	  -D SR_SQUELCH=4

[env:GL-C-211WL]
extends = env:esp32dev
build_flags =
	  ${env:esp32dev.build_flags}
	  ${gledopto_flags.build_flags}
      ; button configuration
	  -D BTNPIN=0,-1,-1,-1
	  -D BTNTYPE=2
      ; led configuration
      -D DATA_PINS=19,18,17,16,4
	  -D LED_TYPES=45
	  -D WLED_PRODUCT_NAME="\"GL-C-211WL\""

[env:GL-C-615WL]
extends = env:esp32dev
build_flags =
	  ${env:esp32dev.build_flags}
	  ${gledopto_flags.build_flags}
      ${mic_pdm.build_flags}
      ; button configuration
	  -D RLYPIN=18
	  -D RLYMDE=true
	  -D BTNPIN=17,-1,-1,-1
	  -D BTNTYPE=2
      ; led configuration
	  -D DATA_PINS=16,2
	  -D PIXEL_COUNTS=30,30
	  -D LED_TYPES=22,22
	  -D WLED_PRODUCT_NAME="\"GL-C-615WL\""

[env:GL-C-616WL]
extends = env:esp32_eth
build_flags =
	  ${env:esp32_eth.build_flags}
	  ${gledopto_flags.build_flags}
      ${mic_pdm.build_flags}
      ; button configuration
	  -D RLYPIN=18
	  -D RLYMDE=true
	  -D BTNPIN=17,-1,-1,-1
	  -D BTNTYPE=2
      ; led configuration
	  -D DATA_PINS=16,2
	  -D PIXEL_COUNTS=30,30
	  -D LED_TYPES=22,22
      -D WLED_ETH_DEFAULT=13
	  -D WLED_PRODUCT_NAME="\"GL-C-616WL\""

[env:GL-C-618WL]
extends = env:esp32_eth
build_flags =
	  ${env:esp32_eth.build_flags}
	  ${gledopto_flags.build_flags}
      ${mic_pdm.build_flags}
      ; button configuration
	  -D RLYPIN=18
	  -D RLYMDE=true
	  -D BTNPIN=17,-1,-1,-1
	  -D BTNTYPE=2
      ; led configuration
	  -D DATA_PINS=16,12,4,2
	  -D PIXEL_COUNTS=30,30,30,30
	  -D LED_TYPES=22,22,22,22
      ; Ethernet configuration
      -D WLED_ETH_DEFAULT=13 ; gledopto ethernet
	  -D WLED_PRODUCT_NAME="\"GL-C-618WL\""

[env:GL-C-620WL]
extends = env:esp32_eth
build_flags =
	  ${env:esp32_eth.build_flags}
	  ${gledopto_flags.build_flags}
      ${mic_pdm.build_flags}
      ; button configuration
	  -D RLYPIN=18
	  -D RLYMDE=true
	  -D BTNPIN=17,-1,-1,-1
	  -D BTNTYPE=2
      ; led configuration
	  -D DATA_PINS=2,4,16
	  -D PIXEL_COUNTS=1,30
      -D LED_TYPES=42,22
      ; Ethernet configuration
      -D WLED_ETH_DEFAULT=13 ; gledopto ethernet
      -D WLED_BOOT_PRESET=1
	  -D WLED_PRODUCT_NAME="\"GL-C-620WL\""