[platformio]
default_envs = 
	gledopto
	gledopto_eth

[custom_flags]
build_flags =
 -D WLED_BRAND="\"GLEDOPTO\""
 -D SERVERNAME='"WLED-Gledopto"'
 # relay configuration
 -D RLYPIN=18
 -D RLYMDE=true
 # microphone configuration
 -D UM_AUDIOREACTIVE_ENABLE=true
 -D SR_DMTYPE=5
 -D I2S_SDPIN=32
 -D I2S_WSPIN=15
 -D I2S_CKPIN=-1
 -D MCLK_PIN=-1
 -D SOUND_AGC=2
 -D SR_SQUELCH=4
 # button configuration
 -D BTNPIN=17
 -D BTNTYPE=2
 # LED configuration
 -D DEFAULT_LED_PIN=16,14,4,2
 -D DEFAULT_LED_TYPE=22 #WS2811
 -D DEFAULT_LED_COLOR_ORDER=0 #GRB
 -D DEFAULT_LED_COUNT=30


[env:gledopto]
extends = env:esp32dev
build_unflags = ${env:esp32dev.build_unflags}
build_flags = ${env:esp32dev.build_flags}
 ${custom_flags.build_flags}
 -D WLED_PRODUCT_NAME="\"GLED\""
 -D WLED_RELEASE_NAME="\"ESP32\""

[env:gledopto_eth]
extends = env:esp32_eth
build_unflags = ${env:esp32_eth.build_unflags}
build_flags = ${env:esp32_eth.build_flags}
 ${custom_flags.build_flags}
 -D WLED_PRODUCT_NAME="\"GLED_Ethernet\""
 -D WLED_RELEASE_NAME="\"ESP32_Ethernet\""
# Gledopto Ethernet
 -D WLED_ETH_DEFAULT=13
